package com.box.androidsdk.share.usx.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.Nullable;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.ViewModelProviders;

import com.box.androidsdk.content.models.BoxItem;
import com.box.androidsdk.content.models.BoxSharedLink;
import com.box.androidsdk.share.R;
import com.box.androidsdk.share.databinding.UsxFragmentSharedLinkAccessBinding;
import com.box.androidsdk.share.utils.FragmentCallback;
import com.box.androidsdk.share.vm.AccessLevelShareVM;

import java.util.HashSet;

import static com.box.androidsdk.content.models.BoxSharedLink.Access.COLLABORATORS;
import static com.box.androidsdk.content.models.BoxSharedLink.Access.COMPANY;
import static com.box.androidsdk.content.models.BoxSharedLink.Access.OPEN;

public class SharedLinkAccessFragment extends BoxFragment {

    private static final String DATE_FRAGMENT_TAG = "datePicker";
    private static final String PASSWORD_FRAGMENT_TAG = "passwordFrag";
    private static final String ACCESS_RADIAL_FRAGMENT_TAG = "accessFrag";


    private boolean mPasswordProtectedLinksSupported = false;
    AccessLevelShareVM mAccessLevelShareVM;
    UsxFragmentSharedLinkAccessBinding binding;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.usx_fragment_shared_link_access, container, false);
        binding.setLifecycleOwner(getViewLifecycleOwner());
        View view = binding.getRoot();
        mAccessLevelShareVM = ViewModelProviders.of(getActivity()).get(AccessLevelShareVM.class);
        setupUi();
        return view;
    }

    private void setupUi() {
        binding.accessRadioGroup.setViewModel(mAccessLevelShareVM);
        if (mAccessLevelShareVM.getSelectedAccess().getValue() == null) mAccessLevelShareVM.setSelectedAccess(mShareItem.getSharedLink().getEffectiveAccess());
        if (mAccessLevelShareVM.getActiveRadioButtons().isEmpty()) mAccessLevelShareVM.setActiveRadioButtons(generateActiveButtons());
    }

    public HashSet<BoxSharedLink.Access> generateActiveButtons() { //move to VM in the future
        HashSet<BoxSharedLink.Access> activeRadioButtons = new HashSet<>();
        new HashSet<>(3); //will be generated by ViewModel
        for (BoxSharedLink.Access access : mShareItem.getAllowedSharedLinkAccessLevels()){
            switch (access){
                case OPEN:
                    activeRadioButtons.add(OPEN);
                    break;
                case COMPANY:
                    activeRadioButtons.add(COMPANY);
                    break;
                case COLLABORATORS:
                    activeRadioButtons.add(COLLABORATORS);
                    break;
            }
        }
        return activeRadioButtons;
    }



    public static SharedLinkAccessFragment newInstance(BoxItem boxItem) {
        Bundle args = BoxFragment.getBundle(boxItem);
        SharedLinkAccessFragment fragment = new SharedLinkAccessFragment();
        fragment.setArguments(args);
        return fragment;
    }

    /**
     * Callback for updating shared link access
     */
    @Override
    public void onDestroy() {
        super.onDestroy();
        if (mFragmentCallback != null) mFragmentCallback.callBack();
    }

}
